In [1]:
import pandas as pd

In [2]:
#Leemos CSV1 
df1=pd.read_csv('Csvs/AnnualTicketSales.csv')
#Quitamos columnas undifined
df1=df1.drop(['Unnamed: 5'],axis=1)
df1

,YEAR,TICKETS SOLD,TOTAL BOX OFFICE,TOTAL INFLATION ADJUSTED BOX OFFICE,AVERAGE TICKET PRICE
0,2021,"42,37,74,881","$3,881,777,912","$3,881,777,912",$9.16
1,2020,"22,36,38,958","$2,048,534,616","$2,048,534,616",$9.16
2,2019,"1,22,85,41,629","$11,253,443,955","$11,253,444,050",$9.16
3,2018,"1,31,15,36,128","$11,948,096,650","$12,013,670,952",$9.11
4,2017,"1,22,56,39,761","$10,993,991,460","$11,226,860,216",$8.97
5,2016,"1,30,25,56,378","$11,267,115,924","$11,931,416,424",$8.65
6,2015,"1,32,33,56,776","$11,155,900,636","$12,121,948,075",$8.43
7,2014,"1,25,74,02,920","$10,272,985,008","$11,517,810,744",$8.17
8,2013,"1,33,91,68,926","$10,887,446,341","$12,266,787,382",$8.13
9,2012,"1,38,09,21,942","$10,992,141,616","$12,649,244,986",$7.96
10,2011,"1,28,29,15,168","$10,173,519,704","$11,751,502,955",$7.93
11,2010,"1,32,85,49,021","$10,482,254,025","$12,169,509,032",$7.89
12,2009,"1,41,85,67,388","$10,639,257,284","$12,994,051,137",$7.50
13,2008,"1,35,80,42,073","$9,750,744,148","$12,439,665,380",$7.18
14,2007,"1,42,00,36,680","$9,769,854,914","$13,007,535,993",$6.88
15,2006,"1,39,87,38,283","$9,161,738,221","$12,812,442,671",$6.55
16,2005,"1,37,29,80,280","$8,800,805,718","$12,576,499,367",$6.41
17,2004,"1,49,56,51,298","$9,287,996,519","$13,700,165,883",$6.21
18,2003,"1,52,45,89,620","$9,193,277,289","$13,965,240,914",$6.03
19,2002,"1,57,57,56,527","$9,155,147,215","$14,433,929,789",$5.81
20,2001,"1,46,58,74,205","$8,296,849,636","$13,427,407,722",$5.66
21,2000,"1,39,74,60,079","$7,532,311,479","$12,800,734,319",$5.39
22,1999,"1,44,46,64,086","$7,338,894,852","$13,233,123,027",$5.08
23,1998,"1,44,38,32,471","$6,771,575,283","$13,225,505,439",$4.69
24,1997,"1,35,73,49,648","$6,230,235,770","$12,433,322,785",$4.59
25,1996,"1,30,52,21,290","$5,769,078,886","$11,955,781,912",$4.42
26,1995,"1,22,17,05,907","$5,314,421,390","$11,190,826,105",$4.35

In [3]:
#Leemos CVS2
df2=pd.read_csv('Csvs/HighestGrossers.csv')
df2

,YEAR,MOVIE,GENRE,MPAA RATING,DISTRIBUTOR,TOTAL FOR YEAR,TOTAL IN 2019 DOLLARS,TICKETS SOLD
0,1995,Batman Forever,Drama,PG-13,Warner Bros.,"$184,031,112","$387,522,978","4,23,06,002"
1,1996,Independence Day,Adventure,PG-13,20th Century Fox,"$306,169,255","$634,504,608","6,92,69,062"
2,1997,Men in Black,Adventure,PG-13,Sony Pictures,"$250,650,052","$500,207,943","5,46,07,854"
3,1998,Titanic,Adventure,PG-13,Paramount Pictures,"$443,319,081","$865,842,808","9,45,24,324"
4,1999,Star Wars Ep. I: The Phantom Menace,Adventure,PG,20th Century Fox,"$430,443,350","$776,153,749","8,47,32,942"
5,2000,How the Grinch Stole Christmas,Adventure,PG,Universal,"$253,367,455","$430,583,644","4,70,06,948"
6,2001,Harry Potter and the Sorcerer’s Stone,Adventure,PG,Warner Bros.,"$300,404,434","$486,166,890","5,30,74,988"
7,2002,Spider-Man,Adventure,PG-13,Sony Pictures,"$403,706,375","$636,480,273","6,94,84,746"
8,2003,Finding Nemo,Adventure,G,Walt Disney,"$339,714,367","$516,050,346","5,63,37,374"
9,2004,Shrek 2,Adventure,PG,Dreamworks SKG,"$441,226,247","$650,826,473","7,10,50,925"
10,2005,Star Wars Ep. III: Revenge of the Sith,Action,PG-13,20th Century Fox,"$380,270,577","$543,413,171","5,93,24,582"
11,2006,Pirates of the Caribbean: Dead Man’s Chest,Action,PG-13,Walt Disney,"$423,315,812","$591,995,851","6,46,28,368"
12,2007,Spider-Man 3,Adventure,PG-13,Sony Pictures,"$336,530,303","$448,054,878","4,89,14,288"
13,2008,The Dark Knight,Adventure,PG-13,Warner Bros.,"$531,001,578","$677,433,772","7,39,55,652"
14,2009,Transformers: Revenge of the Fallen,Action,PG-13,Paramount Pictures,"$402,111,870","$491,112,631","5,36,14,916"
15,2010,Toy Story 3,Action,G,Walt Disney,"$415,004,880","$481,805,411","5,25,98,844"
16,2011,Harry Potter and the Deathly Hallows: Part II,Action,PG-13,Warner Bros.,"$381,011,219","$440,108,798","4,80,46,812"
17,2012,The Avengers,Adventure,PG-13,Walt Disney,"$623,357,910","$717,331,462","7,83,11,295"
18,2013,Iron Man 3,Adventure,PG-13,Walt Disney,"$408,992,272","$460,808,016","5,03,06,552"
19,2014,Guardians of the Galaxy,Adventure,PG-13,Walt Disney,"$333,055,258","$373,413,235","4,07,65,637"
20,2015,Star Wars Ep. VII: The Force Awakens,Action,PG-13,Walt Disney,"$742,208,942","$806,480,887","8,80,43,765"
21,2016,Finding Dory,Action,PG,Walt Disney,"$486,295,561","$514,967,322","5,62,19,140"
22,2017,Star Wars Ep. VIII: The Last Jedi,Action,PG-13,Walt Disney,"$517,218,368","$528,173,936","5,76,60,910"
23,2018,Black Panther,Action,PG-13,Walt Disney,"$700,059,566","$703,901,821","7,68,45,177"
24,2019,Avengers: Endgame,NaN,PG-13,Walt Disney,"$858,373,000","$858,373,002","9,37,08,843"
25,2020,Bad Boys For Life,NaN,R,Sony Pictures,"$204,417,855","$204,417,848","2,23,16,359"
26,2021,Shang-Chi and the Legend of the Ten Rings,NaN,PG-13,Walt Disney,"$224,226,704","$224,226,704","2,44,78,897"

In [4]:
#Hacemo inner join
df12 = pd.merge(df1,df2,on=['YEAR'],how ="inner")
#Quitamos columnas que no se ocuparan
df12=df12.drop(['GENRE','MPAA RATING','TOTAL IN 2019 DOLLARS','AVERAGE TICKET PRICE','TOTAL INFLATION ADJUSTED BOX OFFICE','TOTAL FOR YEAR','TOTAL BOX OFFICE'],axis=1)
df12

,YEAR,TICKETS SOLD_x,MOVIE,DISTRIBUTOR,TICKETS SOLD_y
0,2021,"42,37,74,881",Shang-Chi and the Legend of the Ten Rings,Walt Disney,"2,44,78,897"
1,2020,"22,36,38,958",Bad Boys For Life,Sony Pictures,"2,23,16,359"
2,2019,"1,22,85,41,629",Avengers: Endgame,Walt Disney,"9,37,08,843"
3,2018,"1,31,15,36,128",Black Panther,Walt Disney,"7,68,45,177"
4,2017,"1,22,56,39,761",Star Wars Ep. VIII: The Last Jedi,Walt Disney,"5,76,60,910"
5,2016,"1,30,25,56,378",Finding Dory,Walt Disney,"5,62,19,140"
6,2015,"1,32,33,56,776",Star Wars Ep. VII: The Force Awakens,Walt Disney,"8,80,43,765"
7,2014,"1,25,74,02,920",Guardians of the Galaxy,Walt Disney,"4,07,65,637"
8,2013,"1,33,91,68,926",Iron Man 3,Walt Disney,"5,03,06,552"
9,2012,"1,38,09,21,942",The Avengers,Walt Disney,"7,83,11,295"
10,2011,"1,28,29,15,168",Harry Potter and the Deathly Hallows: Part II,Warner Bros.,"4,80,46,812"
11,2010,"1,32,85,49,021",Toy Story 3,Walt Disney,"5,25,98,844"
12,2009,"1,41,85,67,388",Transformers: Revenge of the Fallen,Paramount Pictures,"5,36,14,916"
13,2008,"1,35,80,42,073",The Dark Knight,Warner Bros.,"7,39,55,652"
14,2007,"1,42,00,36,680",Spider-Man 3,Sony Pictures,"4,89,14,288"
15,2006,"1,39,87,38,283",Pirates of the Caribbean: Dead Man’s Chest,Walt Disney,"6,46,28,368"
16,2005,"1,37,29,80,280",Star Wars Ep. III: Revenge of the Sith,20th Century Fox,"5,93,24,582"
17,2004,"1,49,56,51,298",Shrek 2,Dreamworks SKG,"7,10,50,925"
18,2003,"1,52,45,89,620",Finding Nemo,Walt Disney,"5,63,37,374"
19,2002,"1,57,57,56,527",Spider-Man,Sony Pictures,"6,94,84,746"
20,2001,"1,46,58,74,205",Harry Potter and the Sorcerer’s Stone,Warner Bros.,"5,30,74,988"
21,2000,"1,39,74,60,079",How the Grinch Stole Christmas,Universal,"4,70,06,948"
22,1999,"1,44,46,64,086",Star Wars Ep. I: The Phantom Menace,20th Century Fox,"8,47,32,942"
23,1998,"1,44,38,32,471",Titanic,Paramount Pictures,"9,45,24,324"
24,1997,"1,35,73,49,648",Men in Black,Sony Pictures,"5,46,07,854"
25,1996,"1,30,52,21,290",Independence Day,20th Century Fox,"6,92,69,062"
26,1995,"1,22,17,05,907",Batman Forever,Warner Bros.,"4,23,06,002"

In [5]:
#agregamos una columna nueva donde conoscamos el porcentaje de lo que significo esa pelicula
#estas dos siguientes lineas son parceos
df12['TICKETS SOLD_y']=df12['TICKETS SOLD_y'].replace('[\$,]', '', regex=True).astype(float)
df12['TICKETS SOLD_x']=df12['TICKETS SOLD_x'].replace('[\$,]', '', regex=True).astype(float)
#operacion para el porcentaje
df12['PORXYEAR']=df12['TICKETS SOLD_y']*100/df12['TICKETS SOLD_x']
df12

,YEAR,TICKETS SOLD_x,MOVIE,DISTRIBUTOR,TICKETS SOLD_y,PORXYEAR
0,2021,4.237749e+08,Shang-Chi and the Legend of the Ten Rings,Walt Disney,24478897.0,5.776392
1,2020,2.236390e+08,Bad Boys For Life,Sony Pictures,22316359.0,9.978744
2,2019,1.228542e+09,Avengers: Endgame,Walt Disney,93708843.0,7.627649
3,2018,1.311536e+09,Black Panther,Walt Disney,76845177.0,5.859173
4,2017,1.225640e+09,Star Wars Ep. VIII: The Last Jedi,Walt Disney,57660910.0,4.704556
5,2016,1.302556e+09,Finding Dory,Walt Disney,56219140.0,4.316062
6,2015,1.323357e+09,Star Wars Ep. VII: The Force Awakens,Walt Disney,88043765.0,6.653063
7,2014,1.257403e+09,Guardians of the Galaxy,Walt Disney,40765637.0,3.242050
8,2013,1.339169e+09,Iron Man 3,Walt Disney,50306552.0,3.756550
9,2012,1.380922e+09,The Avengers,Walt Disney,78311295.0,5.670943
10,2011,1.282915e+09,Harry Potter and the Deathly Hallows: Part II,Warner Bros.,48046812.0,3.745128
11,2010,1.328549e+09,Toy Story 3,Walt Disney,52598844.0,3.959120
12,2009,1.418567e+09,Transformers: Revenge of the Fallen,Paramount Pictures,53614916.0,3.779511
13,2008,1.358042e+09,The Dark Knight,Warner Bros.,73955652.0,5.445756
14,2007,1.420037e+09,Spider-Man 3,Sony Pictures,48914288.0,3.444579
15,2006,1.398738e+09,Pirates of the Caribbean: Dead Man’s Chest,Walt Disney,64628368.0,4.620476
16,2005,1.372980e+09,Star Wars Ep. III: Revenge of the Sith,20th Century Fox,59324582.0,4.320862
17,2004,1.495651e+09,Shrek 2,Dreamworks SKG,71050925.0,4.750501
18,2003,1.524590e+09,Finding Nemo,Walt Disney,56337374.0,3.695248
19,2002,1.575757e+09,Spider-Man,Sony Pictures,69484746.0,4.409612
20,2001,1.465874e+09,Harry Potter and the Sorcerer’s Stone,Warner Bros.,53074988.0,3.620706
21,2000,1.397460e+09,How the Grinch Stole Christmas,Universal,47006948.0,3.363742
22,1999,1.444664e+09,Star Wars Ep. I: The Phantom Menace,20th Century Fox,84732942.0,5.865235
23,1998,1.443832e+09,Titanic,Paramount Pictures,94524324.0,6.546765
24,1997,1.357350e+09,Men in Black,Sony Pictures,54607854.0,4.023124
25,1996,1.305221e+09,Independence Day,20th Century Fox,69269062.0,5.307074
26,1995,1.221706e+09,Batman Forever,Warner Bros.,42306002.0,3.462863

In [6]:
#borramos columnas ya no necesario
df12=df12.drop(['TICKETS SOLD_x'], axis=1)
df12=df12.drop(['TICKETS SOLD_y'], axis=1)
df12

,YEAR,MOVIE,DISTRIBUTOR,PORXYEAR
0,2021,Shang-Chi and the Legend of the Ten Rings,Walt Disney,5.776392
1,2020,Bad Boys For Life,Sony Pictures,9.978744
2,2019,Avengers: Endgame,Walt Disney,7.627649
3,2018,Black Panther,Walt Disney,5.859173
4,2017,Star Wars Ep. VIII: The Last Jedi,Walt Disney,4.704556
5,2016,Finding Dory,Walt Disney,4.316062
6,2015,Star Wars Ep. VII: The Force Awakens,Walt Disney,6.653063
7,2014,Guardians of the Galaxy,Walt Disney,3.242050
8,2013,Iron Man 3,Walt Disney,3.756550
9,2012,The Avengers,Walt Disney,5.670943
10,2011,Harry Potter and the Deathly Hallows: Part II,Warner Bros.,3.745128
11,2010,Toy Story 3,Walt Disney,3.959120
12,2009,Transformers: Revenge of the Fallen,Paramount Pictures,3.779511
13,2008,The Dark Knight,Warner Bros.,5.445756
14,2007,Spider-Man 3,Sony Pictures,3.444579
15,2006,Pirates of the Caribbean: Dead Man’s Chest,Walt Disney,4.620476
16,2005,Star Wars Ep. III: Revenge of the Sith,20th Century Fox,4.320862
17,2004,Shrek 2,Dreamworks SKG,4.750501
18,2003,Finding Nemo,Walt Disney,3.695248
19,2002,Spider-Man,Sony Pictures,4.409612
20,2001,Harry Potter and the Sorcerer’s Stone,Warner Bros.,3.620706
21,2000,How the Grinch Stole Christmas,Universal,3.363742
22,1999,Star Wars Ep. I: The Phantom Menace,20th Century Fox,5.865235
23,1998,Titanic,Paramount Pictures,6.546765
24,1997,Men in Black,Sony Pictures,4.023124
25,1996,Independence Day,20th Century Fox,5.307074
26,1995,Batman Forever,Warner Bros.,3.462863